### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Ghostlyr** [jm-organization/webmcr_gm_edition#1]
# База данных:
- [x] Полностью уникальные `uuid`, `login` и `email`
- [-] Установить атрибут `UNSIGNED` для всех колонок, где не требуются отрицательные значения (?)
- [x] **Смена типов данных**:
  - [x] В поле `gender` таблицы `mcr_users` использовать ENUM для удобства разработки 
  - [x] UUID в `mcr_users` преобразовать в бинарный формат binary(16)
- [x] **Изменить длины полей IP для поддержки IPv6** (в бинарный вид?):
  - [x] mcr_news_views
  - [x] mcr_news_votes
  - [x] mcr_users
- [x] **MCR_USERS**: 
  - [x] Вырезать избыточные данные: 
    - [x] `firstname`, `lastname`, `birthday` (ненадобность, 152-ФЗ РФ)
    - [x] `color` (ненадобность)
    - [-] Добавить поле `comments` для хранения "кэша" количества комментариев, оставленных пользователем (?)
    - [-] Хранить ip регистрации (`ip_create`), не имеет особого смысла. Реализовать хранение изменения IP-адресов пользователей в отдельной таблице, подчищаемой от устарелых данных через CRON (?) 
- [x] **MCR_NEWS**:
  - [x] Удалить колонки `text_bb`, `text_bb_short`, `text_html_short` в виду грядущих изменений CMS
  - [x] Сменить тип `text_html` на TEXT | MEDIUMTEXT - с головой хватает.
  - [x] Вынести дату создания из `data` в отдельную колонку
  - [x] Добавить колонку для миниатюры изображения новости - `img` varchar(255)
  - [x] Добавить поле-активатор `hidden` tinyint для скрытия новостей от пользователей (TODO CMS*)
  - [ ] Добавить поле-активатор tinyint для автоматического закрытия комментариев к новости (TODO CMS*)
  - [x] Добавить дополнительные поля для хранения "кэша" количества просмотров, лайков и дизлайков (TODO CMS*)
- [x] **MCR_NEWS_CATS**:
  - [x] Добавить поле-активатор `hidden` tinyint для скрытых категорий выводе главной страницы модуля (TODO CMS*)
- [x] **MCR_COMMENTS**:
  - [x] Переименовать в MCR_NEWS_COMMENTS, поскольку таблица используются только для новостей
  - [x] Вынести дату создания в отдельную колонку
- [x] **MCR_FILES**:
  - [x] Добавить колонку для хранения хеш-суммы размера файла (MD5)

# CMS:
**Модули**:
- [ ] **Модуль «Регистрация»:**
  - [x] Исключить удаленные в БД поля данных
  - [x] Адаптировать код под преобразованные типы в БД
  - [ ] Черный/белый список почтовых доменов
  - [ ] Список запрещенных к регистрации никнеймов с масками
  - [x] Не вставлять значение `date_last` с текущим временем прямо в момент регистрации (необходимость знать, производился ли вход в аккаунт после регистрации)
  - [x] Генерировать UUID функцией UUID MySQL (`UNHEX(REPLACE(UUID(), '-', ''))` для бинарного вида), вместо использования функции `logintouuid`
- [ ] **Модуль «Новости»:**
  - [x] Убрать краткую новость, заменить обрезанием текста до специальной фразы ([AltNews](https://github.com/qexyorg/webMCR-AltNews/))
  - [x] Исключить лишние запросы `COUNT(*)`, оптимизировав получение данных о количестве просмотров, лайков, дизлайков, храня "кеш" в массиве `data` ([AltNews](https://github.com/qexyorg/webMCR-AltNews/)) или в собственных колонках таблицы `mcr_news`  (?)
  - [x] Убрать все связанное с BB-парсером в добавлении и редактировании новости, заменить фильтром HTML ([htmLawed](http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/)/HTMLPurifier?)
  - [x] Добавить проверку длины названия новости (принимает пустое поле)
  - [ ] Добавить поле для указания URL картинки-миниатюры новости + вывод в массиве новостей
  - [x] Вынести дату создания новости в отдельную колонку (TODO БД*)
  - [x] Вынести дату создания комментария в отдельную колонку (TODO БД*)
  - [x] Добавить возможность указания даты публикации ([с валидацией времени](http://php.net/manual/en/function.checkdate.php)) и проверку даты создания новости в выводе на главной и в категориях >= NOW, для "запланированных" новостей
  - [ ] Добавить опцию закрытия возможности комментирования через указанное в конфигурации количество дней на странице добавления/редактирования новости
  - [ ] Добавить отключение детальной истории просмотров, заменяемую на простой вариант
  - [ ] Добавить "скрытые" на вывод главной страницы категории новостей
  - [ ] Добавить опции ограничения:
    - [ ] Количества символов в сообщении комментария (добавление + редактирование)
    - [ ] Частоты комментирования и право игнорирования ограничения
    - [ ] Частоты редактирования комментариев и право игнорирования ограничения
    - [ ] Частоты лайков и право игнорирования ограничения
  - [ ] Добавить список запрещенных в комментариях слов с конфигурируемым действием - отклонение комментария, замена запрещенных слов.
  - [ ] RSS-лента новостей
- [x] **Модуль «Статические страницы»:**
  - [x] Убрать все связанное с BB-парсером, заменить фильтром HTML ([htmLawed](http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/)/HTMLPurifier?)
- [ ] **Модуль «Восстановление пароля»:**
  - [ ] В текущей сброс невозможен, если аккаунт был взломан и злоумышленник сбрасывает сессию `tmp` быстрее, чем пользователь проходит по ссылке сброса
  - [ ] Добавить капчу (зависимую от выбранной в основных настройках CMS)
- [ ] **Модуль «Админ-панель»:**
  - [ ] Панель управления пользователями:
    - [ ] Добавить функцию массовой повторной отправки писем подтверждения аккаунта для непроверенных пользователей
    - [ ] Добавить функции просмотра/удаления установленных у пользователя скина/плаща на странице редактирования пользователя.
  - [ ] Выделить отдельные шаблоны постраничной навигации и блока уведомлений, так как они могут быть несовместимы с установленной темой.

**Блоки**:
- [ ] Ошибка при редактировании данных блока? `Warning: Cannot modify header information - headers already sent by (output started at /modules/admin/blocks.class.php:128) in /engine/core.class.php on line 170`
- [ ] **Блок оповещения**:  Вынести типы уведомлений в разные шаблоны
- [ ] **Блок мониторинга**: 
  - [ ] Мониторинг серверов выполняет свою работу дважды: сначала запрос выполняет блок, а после загрузки страницы вызывается AJAX-скрипт мониторинга, перебирающий таблицу серверов для обновления данных, что можно было бы использовать и для вывода, вывесив весь функционал на AJAX-скрипт.

**Ядро и API**:
- [ ] Добавить функцию проверки на брут, выводя капчу при большом количестве неудачных попыток входа (?)
- [ ] Страница 404 не отдает HTTP заголовок 404 [core.class.php#L462](https://github.com/jm-organization/webmcr_gm_edition/blob/master/upload/engine/core.class.php#L462) и во всех модулях (SEO)
- [ ] Оптимизировать выборку для таблиц с большим количеством записей [(example)](https://habrahabr.ru/post/217521/):
  - [ ] Список пользователей
- [ ] Заменить ограничение количества регистраций с одного IP на конфигурируемую временную блокировку IP-адреса при пересечении указанного лимита количества аккаунтов.
- [ ] **Парсер BB-кодов**:
  - [ ] Поддержка тега `color` с и без двойных кавычек `[color=#ff0000]123[/color]` 
  - [ ] Поддержка тега `size` с и без двойных кавычек `[size=3]123[/size]`
- [x] Лог ошибок SQL-запросов
- [ ] Функция отправки e-mail (`send_mail`):
  - [ ] Название сайта поместить квадратные скобки в subject отправляемых писем через в модулях  `"[{$this->cfg['main']['s_name']}] {фраза модуля}"`
  - [ ] Убрать квадратные скобки из фраз subject писем
  - [ ] Объединить все фразы `msg` в одну, данные выводить переменными внутри самих фраз.
  - [ ] **Добавить модуль временной/перманентной блокировки IP-адресов**:
- [ ] Реализовать блокировку по типам: полного доступа к сайту/регистрации
- [ ] Интегрировать функцию массовой блокировки по IP пользователя в администрирование пользователями
- [ ] Добавить страницу со списком заблокированных адресов в админ-панели
- [ ] **Пагинация**:
  - [ ] Исключить выход за пределы последней страницы - отправлять на последнюю, если значение больше максимального (SEO)
- [ ] Добавить функцию для получения ссылки на буферизованный скин пользователя по его логину или ID, с доп. параметрами - пол, миниатюра или полный скин. Сейчас это возможно только дублированием [подобного кода](https://github.com/jm-organization/webmcr_gm_edition/blob/master/modules/users.php#L82) из модуля пользователей.  Еще что-то придумать нужно с обновлением кешированных картинок, типа еще одного входящего параметра - даты обновления образа, хранимой в БД.
- [ ] Переработать логику работы с функцией загрузки шаблона `$core->sp()`: проверять существование указанного файла, а при отсутствии выдавать шаблон темы по умолчанию. 
Текущая система загрузки HTML-шаблонов имеет серьезный недостаток - требует наличие КАЖДОГО шаблона в выбранной теме, включая админ-панель. Для верстальщика это приводит к дублированию файлов и к трудностям с поддержкой - после каждого изменения нетронутого основного шаблона он должен быть обновлен и в кастомной теме. А разработчика заставляет постоянно передавать константу MCR_THEME_PATH.
- [ ] Вынести во всех шаблонах лишние ресурсы из `HEADER` и `DEF_HEADER` в новые переменные перед тегом `</body>`: в `<header>`  должны находиться только критично важные для отображения страницы ресурсы - в данном случае только основной CSS, дабы избежать подергивания страницы при загрузке.
- [ ] Добавить функцию для получения UUID текущего пользователя с опциональным аргументом для отключения разделения черточками (требуется так как многие плагины тоже хранят UUID в бинарном виде). Из базы BINARY значение должно извлекаться функцией HEX(`uuid`), чтобы получить чистую строку, разбирать лучше на стороне PHP и желательно заменой регулярным выражением (производительность на стороне preg_replace против substr: https://wtools.io/php-sandbox/eE)
- [ ] Добавить функцию обновления баланса пользователя с различными вариантами действия (списать со счета/прибавить сумму/установить заданное число) и с возможностью указания валюты.
- [ ] Добавить функцию парсинга цветовых кодов Minecraft. Есть библиотека с совместимой лицензией: [Spirit55555/PHP-Minecraft](https://github.com/Spirit55555/PHP-Minecraft/blob/master/src/MinecraftColors.php)
Цветовые коды могут использоваться модуле мониторинга - в названиях серверов, также собирается информация о MOTD сервера, но она только хранится в базе данных без вывода где-либо. В сторонних модулях функция тоже окажется полезна - для вывода чата игры, префиксов-суффиксов.

# Написание сторонних модулей:
- [ ] **Файлы**:
  - [ ] Добавить модуль менеджера файлов
  - [ ] Добавить проверку хеш-суммы файла для исключения дубликатов
  - [ ] Древовидная структура хранения файлов в папках для ускорения работы файловой системы (?)

# Написание документации:
- [ ] Составить краткую документацию по API
- [ ] Добавить пример готового модуля
- [ ] Описать все требования к установщику:
    - [ ] Должен наследовать шаблон админки
    - [ ] Обязательный этап - проверка доступа к чтению и записи конфиг-файла

# Front-End:
- [x] Базировать дефолтный шаблон на bootstrap 4
- [x] Более практичный и компактный вид настройки привилегий групп
- [x] Добавить HTML-редактор новостей (tinyMCE?)
- [x] Добавить HTML-редактор статических страниц (tinyMCE?)
- [x] Добавить визуальный BB-редактор в форму комментариев (WysiBB?)
- [ ] Минимизировать зависимость от иерархии классов и от фреймворка в JS части
- [ ] Строгое именование CSS классов для избежания проблем совместимости
- [x] Замена шрифта
- [ ] Исправление цитирования комментариев к новости (синхронизировать с WysiBB)
- [x] Исправление бага с зацикливанием при переходе в BB-режим WysiBB, вызванным отсутствием символов для обрезки в `transform`. Костыль - лишние пробелы.
```
  '<ul>{SELTEXT}</ul>':" {SELTEXT} ",
  '<li>{SELTEXT}</li>':"[*]{SELTEXT} "
```
- [x] Короткие теги php  в шаблонах?
В инетрнетах много споров на эту тему и хостеров с `short_open_tag = off` , но ИМХО рядовому юзеру удобнее использовать сокращенный вид тегов php
Объем кода сокращается и синтаксис упрощается.

**Comment by Ghostlyr** [comment]
По длине значений полей для IPv6 - максимальная длина IPv6 с учетом IPv4-совместимого IPv6 может составлять 45 символов [см](https://stackoverflow.com/questions/166132/maximum-length-of-the-textual-representation-of-an-ipv6-address), что в общем то все равно довольно ощутимо влияет на объем базы.

https://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html
Функции MySQL `INET6_NTOA(`ip`)` | INET6_ATON(`ip`)` могут распознавать так и IPv4 адресы, для эффективного, производительного и многофункционального хранения в бинарном виде, но хз что в этом плане у PHP.

**Comment by Ghostlyr** [comment]
**Обновление минимальных системных требований в скрипте установки:**
- [x] [Подобные конструкции](https://github.com/jm-organization/webmcr_gm_edition/blob/12696a729b58c1ec25c400fddfd07d367ba9d3f6/engine/l10n.class.php#L23) не поддерживаются до PHP 5.4: `Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in \engine\l10n.class.php on line 23` , `Fatal error: Using $this when not in object context in \engine\l10n.class.php on line 24`
- [x] Для работы локализации требуется установленное расширение `php_intl`
- [x] Функция UNHEX появилась в MySQL 5.6

**FIXED IN DEV**

**Comment by Ghostlyr** [comment]
- [ ] Директории открыты всем желающим:
- /data/logs
- /themes
- /configs

И /uploads наверное стоит [ограничить ](https://stackoverflow.com/a/28096120/8181148)определенным списком расширений файлов

**Comment by Ghostlyr** [comment]
- [ ] Переработать логику работы с функцией загрузки шаблона `$core->sp()`: проверять существование указанного файла, а при отсутствии выдавать шаблон темы по умолчанию. 
Текущая система загрузки HTML-шаблонов имеет серьезный недостаток - требует наличие КАЖДОГО шаблона в выбранной теме, включая админ-панель. Для верстальщика это приводит к дублированию файлов и к трудностям с поддержкой - после каждого изменения нетронутого основного шаблона он должен быть обновлен и в кастомной теме. А разработчика заставляет постоянно передавать константу MCR_THEME_PATH.

**Comment by Ghostlyr** [comment]
- [ ] Вынести во всех шаблонах лишние ресурсы из `HEADER` и `DEF_HEADER` в новые переменные перед тегом `</body>`: в `<header>`  должны находиться только критично важные для отображения страницы ресурсы - в данном случае только основной CSS, дабы избежать подергивания страницы при загрузке.

**Comment by Ghostlyr** [comment]
- [ ] Добавить функцию для получения UUID текущего пользователя с опциональным аргументом для отключения разделения черточками. Требуется так как многие плагины тоже хранят UUID в бинарном виде. Из базы BINARY значение должно извлекаться функцией HEX(`uuid`), чтобы получить чистую строку, разбирать лучше на стороне PHP и желательно заменой регулярным выражением (производительность на стороне preg_replace против substr: https://wtools.io/php-sandbox/eE)

**Comment by Ghostlyr** [comment]
Пожелание от простого любителя и ценителя понятного кода, не вкуривающего суть вещей и не способного оценить практическую пользу:
Для упрощения разработки и логики пригодились бы "типобезопасные" функции для работы с HTTP запросами в духе Laravel. Типа `$core->request->has('param')`, `$core->request->filled('param') (boolean)`, `$core->request->get('param') (trim(string) | string)`.

**Comment by Ghostlyr** [comment]
- [ ] Реорганизовать JS-библиотеки. Крупные и универсальные библиотеки не должны находиться в папке с темами. И папку `language` можно все так же использовать JS-локалей, переместив также туда локализации библиотек.
- [x] Слить папки `uploads` с  `data`.
```
    |-- data
        |-- cache
        |-- logs
        |-- tmp
        |-- uploads
            |-- cloaks
            |-- files
            |-- panel-icons
            |-- skins
            |-- smiles
```
- [ ] Реорганизовать папку `install` для установки модулей. Текущая система вынуждает создавать папку с другим именем для скрипта установки модуля. Было бы удобнее встроить в основной скрипт установки CMS роутинг к скриптам установки модулей.
- [ ] Защитить скрипт переустановки каким-нибудь дополнительным условием. Сейчас любой желающий может выполнить `/install/?do=reinstall`.

**Comment by Ghostlyr** [comment]
- [ ] Добавить функцию парсинга цветовых кодов Minecraft. Есть библиотека с совместимой лицензией: [Spirit55555/PHP-Minecraft](https://github.com/Spirit55555/PHP-Minecraft/blob/master/src/MinecraftColors.php)
Цветовые коды могут использоваться модуле мониторинга - в названиях серверов, также собирается информация о MOTD сервера, но она только хранится в базе данных без вывода где-либо. В сторонних модулях функция тоже окажется полезна - для вывода чата игры, префиксов-суффиксов.
